# Change these first
owner: angelcantu84 # Your GitHub organization or username, where this repository lives
repo: statusmoneybox # The name of this repository

sites:
  - name: API
    url: https://api.moneybox.business
  - name: SANDBOX
    url: https://sandbox.moneybox.business
  - name: DEV
    url: https://dev.moneybox.business
  - name: CORE
    url: https://core.moneybox.business

assignees:
  - angelcantu84
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: angelcantu84.github.io/statusmoneybox
  baseUrl: /statusmoneybox
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: moneyBox Status Services
  introMessage: Este portal proporciona el estatus de nuestros servicios almacenados en AWS Amazon, para brindar mejor disponibilidad hemos colocado este monitor un servicios externo [**Clic para Soporte**](soporte@moneybox.business)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
